// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeU-wfjywxBXqZAwWGh0toBmrThzGe0zw',
    appId: '1:674723513220:web:6d207ff54070eea0d013d1',
    messagingSenderId: '674723513220',
    projectId: 'flutter-preloved-app',
    authDomain: 'flutter-preloved-app.firebaseapp.com',
    storageBucket: 'flutter-preloved-app.firebasestorage.app',
    measurementId: 'G-VPPDPZLTT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmMWMnxIUBoNvVx4yagbfFuvEc_OwKqMI',
    appId: '1:674723513220:android:dce7dee2c9583a78d013d1',
    messagingSenderId: '674723513220',
    projectId: 'flutter-preloved-app',
    storageBucket: 'flutter-preloved-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeSA63fIPjL6-pSrDKy3y-sRBMZmRGUU',
    appId: '1:674723513220:ios:953b544b81adc756d013d1',
    messagingSenderId: '674723513220',
    projectId: 'flutter-preloved-app',
    storageBucket: 'flutter-preloved-app.firebasestorage.app',
    iosBundleId: 'com.example.prelovedMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeSA63fIPjL6-pSrDKy3y-sRBMZmRGUU',
    appId: '1:674723513220:ios:953b544b81adc756d013d1',
    messagingSenderId: '674723513220',
    projectId: 'flutter-preloved-app',
    storageBucket: 'flutter-preloved-app.firebasestorage.app',
    iosBundleId: 'com.example.prelovedMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeU-wfjywxBXqZAwWGh0toBmrThzGe0zw',
    appId: '1:674723513220:web:cc91330804011eafd013d1',
    messagingSenderId: '674723513220',
    projectId: 'flutter-preloved-app',
    authDomain: 'flutter-preloved-app.firebaseapp.com',
    storageBucket: 'flutter-preloved-app.firebasestorage.app',
    measurementId: 'G-HEBGM9KKCL',
  );

}